export const REQUEST_GET_BOOKS = 'REQUEST_GET_BOOKS';
export const SUCCESS_GET_BOOKS = 'SUCCESS_GET_BOOKS';
export const ERROR_GET_BOOKS = 'ERROR_GET_BOOKS';
export const CLEAR_STATE = 'CLEAR_STATE';

export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';