export const REQUEST_GET_BOOK = 'REQUEST_GET_BOOK';
export const SUCCESS_GET_BOOK = 'SUCCESS_GET_BOOK';
export const ERROR_GET_BOOK = 'ERROR_GET_BOOK';
export const CLEAR_STATE = 'CLEAR_STATE';

export const REQUEST_ADD_BOOK = 'REQUEST_ADD_BOOK';
export const SUCCESS_ADD_BOOK = 'SUCCESS_ADD_BOOK';
export const ERROR_ADD_BOOK = 'ERROR_ADD_BOOK';

export const REQUEST_EDIT_BOOK = 'REQUEST_EDIT_BOOK';
export const SUCCESS_EDIT_BOOK = 'SUCCESS_EDIT_BOOK';
export const ERROR_EDIT_BOOK = 'ERROR_EDIT_BOOK';